#import "../Deliverables/DeliverableFragment"

mutation CreateMilestoneParent($input: MilestoneparentInput!) {
  createMilestoneparent(input: $input) {
    id
    title
    rank
    deliverables {
      ...DeliverableFragment
    }
  }
}
