query EditSalary($id: ID!) {
  salary(id: $id) {
    id
    effectiveDate
    hourlyRates
    hourlyRate
    annualBase
    hourlyRates
    annualIncentive
    retroactiveDate
    performancePaySummary
    ptoPlan { id }
  }
}
