#import "./DocumentRowFragment"

mutation CopyDocumentFromLibrary($projectId: ID!, $documentId: ID!) {
  copyDocumentFromLibrary(projectId: $projectId, documentId: $documentId) {
    ...DocumentRowFragment
  }
}
