#import "./DocumentRowFieldsFragment.gql"

fragment DocumentReferenceFragment on DocumentReference {
  id
  rank
  document {
    ...DocumentRowFieldsFragment
    referenceDocument {
      ...DocumentRowFieldsFragment
    }
    project {
      id
      number
    }
  }
}
