query SalesFunnel {
  dynamicMetrics(types:["All Prospects", "Active Opportunities by Stage", "Recent Projects"]) {
    sum
    count
    name
    extraInt
    date
  }
  salesStages {
    id
    probability
    description
  }
}