mutation UpdateUser($input: UserInput!) {
  saveUser(input: $input) {
    id
    timesheetsHideLockedWeeks
    timesheetsScrollToBottom
    taskCompletionNotification
    projectListStartDate
    projectListTotalDue
    showPrimaryContactsOnly
    signature
  }
}
