#import "./TrainingAssignmentFragment"

fragment TrainingPlanFragment on TrainingPlan {
  id
  status
  user {
    id
    login
  }
  name
  trainingAssignments {
    ...TrainingAssignmentFragment
  }
}
