#import "./PhysicalAddressFragment"

fragment ResidenceFragment on Residence {
  id
  primary
  category
  endDate
  physicalAddress {
    ...PhysicalAddressFragment
  }
  residence {
    id
    physicalAddress {
      ...PhysicalAddressFragment
    }
  }
}
