#import "../Documents/AttachedFileFragment"
mutation SaveSourceFile($input: SourceFileInput!) {
  saveSourceFile(input: $input) {
    id
    status
    attachedFiles {
      ...AttachedFileFragment
    }
  }
}
