query KpiSet($id: ID!) {
  kpiSet(id: $id) {
    id
    name
    globalSet
    kpiSections {
      id
      rank
      name
      who
      description
      kpiTypes {
        id
        rank
        title
        valueType
        editable
        description
        hideWhenEmpty
        aggregation
        mode
      }
    }
  }
}
