query KpiSets {
  kpiSets {
    ...KpiSetsFields
  }
}


fragment KpiSetsFields on KpiSet {
  id
  name
  globalSet
  kpiSections {
    id
    rank
    name
    who
    description
    kpiTypes {
      id
      rank
      title
      valueType
      editable
      description
      hideWhenEmpty
      aggregation
      mode
    }
  }
}