#import "../Documents/AttachedFileFragment"
#import "../TenTouches/TenTouchTaskFragment"
#import "./TemplateFields"

query TenTouchTemplates {
  tenTouchTemplates {
    ...TenTouchTemplateFields
  }
}

