#import "../Locations/LocationRowFragment"

query ReportSectionLocations($reportSectionId: ID!) {
  reportSectionLocations(reportSectionId: $reportSectionId) {
    id
    location {
      ...LocationRowFragment
    }
  }
}
