query ReportType($id: ID!) {
  reportType(id: $id) {
    id
    name
    rank
    overhead
    reportTypeSections {
      id
      showHeading
      sectionType
      rank
      template
      title
      prefill
    }
  }
}
