mutation SaveReportTypeSection($input: ReportTypeSectionInput!) {
  saveReportTypeSection(input: $input) {
    id
    showHeading
    sectionType
    rank
    template
    title
    prefill
    includeAnalysisList
  }
}
