mutation SaveRetainer($input: RetainerInput!) {
  saveRetainer(input: $input) {
    id
    amount
    checkDate
    checkNumber
    referenceNumber
    payor
    synced
    payments {
      id
      amount
    }
  }
}
