query PlanTypes {
  planTypes {
    id
    name
    planSections {
      id
      position
      name
      deliverableMenuItems {
        id
        position
        sku {
          id
          name
          description
        }
      }
    }
  }
}
